# Generated by Django 3.1.3 on 2020-11-07 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='UserAnswer',
        ),
    ]
