# Generated by Django 3.1.3 on 2020-11-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_auto_20201107_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztaker',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
