# Generated by Django 3.1.3 on 2020-11-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_quiztaker_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='total_point',
            field=models.IntegerField(default=0),
        ),
    ]
